#!/usr/bin/env bash
#+-----------------------------------------------------------------------+
# Copyright 2026 Noelware, LLC. <team@noelware.org>, et al.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#+-----------------------------------------------------------------------+

set -euo pipefail

required_commands=("bazel" "python3")
for cmd in "${required_commands[@]}"; do
    if ! command -v "$cmd" >/dev/null; then
        echo "[bzl.noelware.cloud:tooling] missing command \`$cmd\`"
        exit 1
    fi
done

[ -z "$1" ] && {
    echo "[bzl.noelware.cloud:tooling] missing tool to call" 2>/dev/null
    exit 1
}

pushd thirdparty/bazel-central-registry

bazel run //tools:$1 -- ${@:2}

popd
