#!/usr/bin/env bash
# +-----------------------------------------------------------------------+
# Copyright 2026 Noelware, LLC. <team@noelware.org>, et al.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# +-----------------------------------------------------------------------+
# This will publish a new version of Noel's `logrin` library
# by:
#
# - Add `source.json` to `modules/logrin/$VERSION/source.json`
# - Downloading the `MODULE.bazel` and placing it in `modules/logrin/$VERSION/MODULE.bazel`
# - Updating the integrity hash in `source.json`

wd=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"/.. &>/dev/null && pwd)

if [ -z "$1" ]; then
    echo "[bazel-registry/tooling:publish-violet] Missing first argument (must be a version string)"
    exit 1
fi

version="$1"
echo "Publishing new logrin version $version"

! [ -d "$wd/modules/logrin/$version" ] && mkdir -p "$wd/modules/logrin/$version"

echo "===> Adding \`source.json\` to new version"

cat <<EOF > "$wd/modules/logrin/$version/source.json"
{
    "integrity": "",
    "url": "https://github.com/auguwu/logrin/releases/download/$version/bazeldist.tgz"
}
EOF

echo "===> Copying \`MODULE.bazel\` from distribution tarball..."
curl -fsSL "https://github.com/auguwu/logrin/releases/download/$version/bazeldist.tgz" | \
    tar -xzO ./MODULE.bazel > "modules/logrin/$version/MODULE.bazel"

echo "===> Updating source integrity..."
"$wd/tools/call-bcr-tool" update_integrity logrin --registry="$wd" --version="$version"

echo "Done."
