name: CI / Modules
on:
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review
jobs:
    validate-module:
        name: "Validate"
        runs-on: ubuntu-latest
        outputs:
            modules: ${{steps.modified.outputs.modules}}
            has_changes: ${{steps.modified.outputs.has_changes}}
        steps:
            - uses: actions/checkout@v6
              with:
                submodules: recursive
                fetch-depth: 0

            - run: .ci/validate-modified.sh
              id: modified
    check:
        name: "Check ${{matrix.module.name}}@${{matrix.module.version}} [${{matrix.runner}} / Bazel v${{matrix.bazel}}]"
        runs-on: ${{matrix.runner}}
        needs: [validate-module]
        if: needs.validate-module.outputs.has_changes == 'true'
        strategy:
            fail-fast: true
            matrix:
                bazel: ["7.7.1", "8.6.0", "9.0.1"]
                runner: [ubuntu-latest, macos-latest, windows-latest]
                module: ${{fromJson(needs.validate-module.outputs.modules)}}
        steps:
            - uses: actions/checkout@v6
              with:
                submodules: recursive

            # Check if we can use `bazel mod` commands on the specified module
            - run: .ci/check-module.sh ${{matrix.module.name}} ${{matrix.module.version}}
              shell: bash

            # Run the presubmit.yml tasks (build/test targets)
            - run: ./tools/call-bcr-tool setup_presubmit_repos --module="${{matrix.module.name}}@${{matrix.module.version}}"
              shell: bash
